language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - sudo redis-server /etc/redis/redis.conf --port 6379

script:
  - ./vendor/bin/phpunit -c phpunit.xml.dist --verbose
